version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: wail
      POSTGRES_PASSWORD: W&88$i&01lo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"    

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 app.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_NAME=mydb
      - DB_USER=wail
      - DB_PASSWORD=W&88$i&01lo
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
