# Generated by Django 5.2 on 2025-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.AddField(
            model_name="project",
            name="creation_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
