# Generated by Django 5.2 on 2025-04-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsDoorsService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows', models.IntegerField()),
                ('windowsTypes', models.CharField(choices=[('PVC', 'Pvc'), ('Aluminum', 'Aluminum'), ('Wood', 'wood')], default='PVC', max_length=100)),
                ('doors', models.IntegerField()),
                ('doorsTypes', models.CharField(choices=[('PVC', 'PVC'), ('Aluminum', 'Aluminum'), ('StandardWood', 'StandardWood'), ('HighEndWood', 'HighEndWood')], default='pvc', max_length=100)),
                ('time', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
