# Generated by Django 5.2 on 2025-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionhouseservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="electricalservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="facadeservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="flooringservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="hvacservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="paintingservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="plumbingservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="roofingservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="windowsdoorsservice",
            name="status",
            field=models.CharField(
                choices=[("Selected", "Selected"), ("NonSelected", "NonSelected")],
                default="NonSelected",
                max_length=100,
            ),
        ),
    ]
