# Generated by Django 5.2 on 2025-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plumbingservice",
            name="sinkCategorie",
        ),
        migrations.RemoveField(
            model_name="plumbingservice",
            name="sinkTypeQuality",
        ),
        migrations.AddField(
            model_name="plumbingservice",
            name="sink",
            field=models.CharField(
                choices=[
                    ("poor_single", "poor_single"),
                    ("poor_double", "poor_double"),
                    ("high_single", "high_single"),
                    ("high_double", "high_double"),
                ],
                default="poor_single",
                max_length=100,
            ),
        ),
    ]
