# Generated by Django 5.2 on 2025-05-04 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoofingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.FloatField()),
                (
                    "roofType",
                    models.CharField(
                        choices=[
                            ("CanalTilesWithInsulation", "Canal tiles with insulation"),
                            ("CanalTilesWithMortar", "Canal tiles with mortar"),
                            ("RomanTiles", "Roman tiles with waterproofing"),
                            ("SlateRoof", "Slate roof"),
                        ],
                        default="CanalTilesWithInsulation",
                        max_length=100,
                    ),
                ),
                ("time", models.FloatField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
