# Generated by Django 5.2 on 2025-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flooringservice",
            name="time",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
