# Generated by Django 5.2 on 2025-05-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionhouseservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="constructionhouseservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="electricalservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="electricalservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="facadeservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="facadeservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="flooringservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="flooringservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="hvacservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="hvacservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="paintingservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="paintingservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="plumbingservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="plumbingservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="roofingservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="roofingservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="windowsdoorsservice",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="windowsdoorsservice",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="Planification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(editable=False)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
    ]
