# Generated by Django 5.2 on 2025-05-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.IntegerField(choices=[('Client', 'Client'), ('Artisan', 'Artisan'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Client', max_length=100),
        ),
    ]
