# Generated by Django 5.2 on 2025-04-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaintingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallSurface", models.FloatField()),
                (
                    "paintingType",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("COLORED", "Basic"),
                            ("DECORATIVE", "Decorative"),
                        ],
                        default="BASIC",
                        max_length=100,
                    ),
                ),
                ("coats", models.IntegerField()),
                ("IswallScrapping", models.BooleanField()),
                ("IsPlastering", models.BooleanField()),
                ("cost", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="electricalservice",
            name="cost",
            field=models.FloatField(),
        ),
    ]
