# Generated by Django 5.2 on 2025-04-30 13:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_windowsdoorsservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsdoorsservice',
            name='windows',
            field=models.IntegerField(validators=[core.models.validate_window]),
        ),
    ]
