# Generated by Django 5.2 on 2025-04-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_paintingservice_alter_electricalservice_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paintingservice",
            name="paintingType",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("COLORED", "Colored"),
                    ("DECORATIVE", "Decorative"),
                ],
                default="BASIC",
                max_length=100,
            ),
        ),
    ]
