# Generated by Django 5.2 on 2025-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_project_start_date_project_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
