# Generated by Django 5.2 on 2025-05-04 21:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_roofingservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roofingservice",
            name="surface",
            field=models.FloatField(validators=[core.models.validate_roof_surface]),
        ),
    ]
