# Generated by Django 5.2 on 2025-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_plumbingservice_sinkcategorie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plumbingservice",
            name="sink",
        ),
        migrations.AddField(
            model_name="plumbingservice",
            name="sinkCategorie",
            field=models.CharField(
                choices=[("POOR", "Poor"), ("NORMAL", "Normal"), ("HIGH", "High")],
                default="single",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="plumbingservice",
            name="sinkTypeQuality",
            field=models.CharField(
                choices=[("POOR", "Poor"), ("NORMAL", "Normal"), ("HIGH", "High")],
                default="poor",
                max_length=100,
            ),
        ),
    ]
