# Generated by Django 5.2 on 2025-05-06 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_roofingservice_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionHouseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.FloatField()),
                ('numberFloors', models.IntegerField()),
                ('houseType', models.CharField(choices=[('Studio', 'Studio'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6')], default='F2', max_length=100)),
                ('groundType', models.CharField(choices=[('GoodSoil', 'GoodSoil'), ('MediumSoil', 'MediumSoil'), ('BadSoil', 'BadSoil')], default='MediumSoil', max_length=100)),
                ('terrainType', models.CharField(choices=[('Flat', 'Flat'), ('Uneven', 'Uneven'), ('Challenging', 'Challenging')], default='MediumSoil', max_length=100)),
                ('cost', models.FloatField()),
                ('time', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
