# Generated by Django 5.2 on 2025-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_paintingservice_paintingtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlooringService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.FloatField()),
                (
                    "floorType",
                    models.CharField(
                        choices=[
                            ("CARRELAGE", "Carrelage"),
                            ("PARQUETBOIS", "ParquetBois"),
                            ("VINYLEPVC", "VinylePVC"),
                            ("MOQUETTE", "Moquette"),
                        ],
                        default="CARRELAGE",
                        max_length=100,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("POOR", "Poor"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                        ],
                        default="POOR",
                        max_length=100,
                    ),
                ),
                ("cost", models.FloatField(editable=False)),
            ],
        ),
    ]
