# Generated by Django 5.2 on 2025-04-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_plumbingservice_sink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plumbingservice",
            name="showerCabinType",
            field=models.CharField(
                choices=[
                    ("Basic_Enclosure", "Basic Enclosure"),
                    ("Luxury_Enclosure", "Luxury Enclosure"),
                ],
                default="Basic_Enclosure",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plumbingservice",
            name="sinkCategorie",
            field=models.CharField(
                choices=[("single", "single"), ("double", "double")],
                default="single",
                max_length=100,
            ),
        ),
    ]
