# Generated by Django 5.2 on 2025-05-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_constructionhouseservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacadeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.FloatField()),
                (
                    "finishing_layer",
                    models.CharField(
                        choices=[
                            ("Enduit Monocouche", "Enduit Monocouche"),
                            ("Acrylic Mortar Coating", "Acrylic Mortar Coating"),
                            ("Lime Plaster", "Lime Plaster"),
                            (
                                "Ventilated Facade(Porcelain)",
                                "Ventilated Facade(Porcelain)",
                            ),
                            (
                                "Ventilated Facade(Terracotta)",
                                "Ventilated Facade(Terracotta)",
                            ),
                        ],
                        default="Enduit Monocouche",
                        max_length=100,
                    ),
                ),
                ("ITE", models.BooleanField(default=False)),
                ("Hydrofuge", models.BooleanField(default=False)),
                ("cost", models.FloatField(blank=True, null=True)),
                ("time", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
