# Generated by Django 5.2 on 2025-05-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_message_receiver_message_room_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
