# Generated by Django 5.2 on 2025-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_facadeservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricalservice",
            name="time",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
