# Generated by Django 5.2 on 2025-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_electricalservice_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="paintingservice",
            name="time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
