# Generated by Django 5.2 on 2025-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_paintingservice_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="hvacservice",
            name="time",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
