# Generated by Django 5.2 on 2025-05-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_message_message_content_message_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constructionhouseservice",
            name="groundType",
        ),
        migrations.RemoveField(
            model_name="constructionhouseservice",
            name="houseType",
        ),
        migrations.RemoveField(
            model_name="constructionhouseservice",
            name="numberFloors",
        ),
        migrations.RemoveField(
            model_name="constructionhouseservice",
            name="surface",
        ),
        migrations.RemoveField(
            model_name="constructionhouseservice",
            name="terrainType",
        ),
        migrations.AddField(
            model_name="constructionhouseservice",
            name="wallConstructionSurface",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="constructionhouseservice",
            name="wallDestructionSurface",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="constructionhouseservice",
            name="cost",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="constructionhouseservice",
            name="time",
            field=models.FloatField(null=True),
        ),
    ]
