# Generated by Django 5.2 on 2025-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tags_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="diplomDocument",
            field=models.FileField(null=True, upload_to="artisan_documents/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(
                choices=[
                    ("Constantine", "Constantine"),
                    ("Algier", "Algier"),
                    ("Annaba", "Annaba"),
                    ("Jijel", "Jijel"),
                    ("Setif", "Setif"),
                ],
                default="Constantine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rating",
            field=models.FloatField(default=5.0, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="roleArtisan",
            field=models.CharField(
                choices=[
                    ("Construction", "Construction"),
                    ("Electricity", "Electricity"),
                    ("Painting", "Painting"),
                    ("Flooring", "Flooring"),
                    ("Hvac", "Hvac"),
                    ("Plumbing", "Plumbing"),
                    ("Carpentary", "Carpentary"),
                    ("Roofing", "Roofing"),
                    ("Tailing", "Tailing"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
