# Generated by Django 5.2 on 2025-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_diplomdocument_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='core.tags'),
        ),
    ]
