# Generated by Django 5.2 on 2025-06-01 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionhouseservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Construction'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Electricity'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facadeservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Facade'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facade_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flooringservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Flooring'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flooring_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hvacservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Hvac'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hvac_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paintingservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Painting'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='painting_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plumbingservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Plumbing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plumbing_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roofingservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Roofing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roofing_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='windowsdoorsservice',
            name='artisan',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Artisan', 'roleArtisan': 'Carpentary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpentary_services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constructionhouseservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roleArtisan',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Electricity', 'Electricity'), ('Painting', 'Painting'), ('Flooring', 'Flooring'), ('Hvac', 'Hvac'), ('Plumbing', 'Plumbing'), ('Carpentary', 'Carpentary'), ('Roofing', 'Roofing'), ('Facade', 'Facade')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricalservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facadeservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facade_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flooringservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flooring_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hvacservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hvac_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paintingservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plumbingservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plumbing_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roofingservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roofing_services_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='windowsdoorsservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpentary_services_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
